version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - ./data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.1
    environment:
      ELASTICSEARCH_HOSTS: "http://es-container:9200"
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          memory: 2G
networks:
  es-net:
    driver: bridge